/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioSettingsRouteImport } from './routes/studio/settings'
import { Route as StudioGalleryRouteImport } from './routes/studio/gallery'
import { Route as StudioBillingRouteImport } from './routes/studio/billing'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as ApiStudioUploadRouteImport } from './routes/api/studio/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGalleryRoute = StudioGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBillingRoute = StudioBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => StudioRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioUploadRoute = ApiStudioUploadRouteImport.update({
  id: '/api/studio/upload',
  path: '/api/studio/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/studio/billing': typeof StudioBillingRoute
  '/studio/gallery': typeof StudioGalleryRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/studio/upload': typeof ApiStudioUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/studio/billing': typeof StudioBillingRoute
  '/studio/gallery': typeof StudioGalleryRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/studio/upload': typeof ApiStudioUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/studio/billing': typeof StudioBillingRoute
  '/studio/gallery': typeof StudioGalleryRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/studio/upload': typeof ApiStudioUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/auth/signin'
    | '/auth/signup'
    | '/studio/billing'
    | '/studio/gallery'
    | '/studio/settings'
    | '/studio/'
    | '/api/auth/$'
    | '/api/studio/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/studio/billing'
    | '/studio/gallery'
    | '/studio/settings'
    | '/studio'
    | '/api/auth/$'
    | '/api/studio/upload'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/auth/signin'
    | '/auth/signup'
    | '/studio/billing'
    | '/studio/gallery'
    | '/studio/settings'
    | '/studio/'
    | '/api/auth/$'
    | '/api/studio/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStudioUploadRoute: typeof ApiStudioUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/gallery': {
      id: '/studio/gallery'
      path: '/gallery'
      fullPath: '/studio/gallery'
      preLoaderRoute: typeof StudioGalleryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/billing': {
      id: '/studio/billing'
      path: '/billing'
      fullPath: '/studio/billing'
      preLoaderRoute: typeof StudioBillingRouteImport
      parentRoute: typeof StudioRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio/upload': {
      id: '/api/studio/upload'
      path: '/api/studio/upload'
      fullPath: '/api/studio/upload'
      preLoaderRoute: typeof ApiStudioUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioBillingRoute: typeof StudioBillingRoute
  StudioGalleryRoute: typeof StudioGalleryRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioBillingRoute: StudioBillingRoute,
  StudioGalleryRoute: StudioGalleryRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStudioUploadRoute: ApiStudioUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
